// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/std.tsx";
import * as $1 from "./pages/artwork.tsx";
import * as $2 from "./pages/translations.tsx";
import * as $3 from "./pages/benchmarks.tsx";
import * as $4 from "./pages/manual.tsx";
import * as $5 from "./pages/x/module.tsx";
import * as $6 from "./pages/x/index.tsx";
import * as $7 from "./pages/index.tsx";

const routes = {
  pages: {
    "./pages/std.tsx": $0,
    "./pages/artwork.tsx": $1,
    "./pages/translations.tsx": $2,
    "./pages/benchmarks.tsx": $3,
    "./pages/manual.tsx": $4,
    "./pages/x/module.tsx": $5,
    "./pages/x/index.tsx": $6,
    "./pages/index.tsx": $7,
  },
  baseUrl: import.meta.url,
};

export default routes;
